@startuml

state TestHFSM {
    state S01 {
        state S11 {
            state S21
            S21 : <b>entry/</b> LOG
            S21 : <b>exit/</b> LOG

            state S22
            S22 : <b>entry/</b> LOG
            S22 : <b>exit/</b> LOG
            S22 : <b>TInternal2/</b> LOG

            [*] --> S21
            S21 -right->S22 : TPeer2
        }
        S11 : <b>entry/</b> LOG
        S11 : <b>exit/</b> LOG

        state S12
        S12 : <b>entry/</b> LOG
        S12 : <b>exit/</b> LOG
        S12 : <b>TInternal1/</b> LOG

        [*] --> S11
        S11 -> S12 : TPeer1
    }
    S01 : <b>entry/</b> LOG
    S01 : <b>exit/</b> LOG

    state S02
    S02 : <b>entry/</b> LOG
    S02 : <b>exit/</b> LOG
    S02 : <b>TInternal0/</b> LOG

    [*] --> S01
    S01 -right-> S02 : TPeer0
}

@enduml
